import Head from "next/head";
import { Inter } from "next/font/google";
import { Input } from '@mujtaba-fleapo/design-system/Input';
import { Accordion } from '@govtechsg/sgds-react/Accordion';
// import { Input as DSInput } from '@fanfix/design-system';
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>DS Client</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Input value={'custom'} id="input" onChange={((e: any) => console.log(e))} />
        </div>
        <div className={styles.description}>
          {/* <Checkbox /> */}
        </div>
        <div className={styles.description}>
        </div>
      </main>
    </>
  );
}
